version: '3.8'
services:
    api:
        container_name: skins_api
        build:
            context: .
            dockerfile: dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - ./src:/app/src